services:
  web:
    build:
      context: ./frontend
    ports:
      - "8080:8080"    
    depends_on:
      - db
  nodebackend: 
    build:
      context: ./backend
    ports: 
      - "3000:3000"    #external:internal 
    depends_on:
      - db
  db:
    volumes:
      - votes_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"  
volumes:
  votes_db: